name: making-impact-optimism

services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    env_file:
      - .env.development
    networks:
      - making-impact-optimism
networks:
  making-impact-optimism:
