name: pipeline CD/CI staging

on:
  pull_request:
    types: [opened, reopened, converted_to_draft, synchronize]
    branches: 
      - develop

jobs:
  # Install dependencies
  call-install-workflow:
    uses: ./.github/workflows/install-deps.yml

  # Build
  call-build-workflow:
    uses: ./.github/workflows/build-staging.yml
    needs: call-install-workflow
