name: debugging ci backup db

on:
  push:
    branches:
      - feat/ci-backup-db

jobs:
  call-backup-db-workflow:
    uses: ./.github/workflows/backup-db.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DB_URL: ${{ secrets.DB_URL }}
      S3_BACKUP_BUCKET: ${{ secrets.S3_BACKUP_BUCKET }}